## --------------------------------------- 
#  Agreement/rules settings are here.
#  World/butcher settings are next section
## ---------------------------------------

# Core plugin Settings
numberOfWarnings: 1
enableNotAgreedKick: true
enableNotAgreedKill: true
debug: true

# Actions to take after the player accepts the rules
transportPlayer: true
transportPlayerToWorld: "world"

changeGameMode: true
changeGameModeTo: "SURVIVAL" # CREATIVE, SURVIVAL, ADVENTURE, SPECTATOR

# The output that will be sent to the player
# Each line can not be any longer than 67 characters (or it will wrap and look bad)
arrayMessageLines:
 - "- No griefing, stealing, cheating, or use of hacking tools"
 - "- Adult content is discussed (sexual, alcohol, drugs, politics)"
 - "- Cursing/foul language is allowed - don't insult others!"
 - "- You must be at least 13 - we reserve the right to ban < 13"
 - "- It is recommended that you be 18 years of age or older"
 - "- This is a very challenging server -- you will die"

# The response that the player must type in order to gain access
stringTextToAccept: "I agree to the rules and am at least 13 years old"

# The various text strings used during the running of the plugin
stringNoChatOrCommandsUntilConfirm: "You cannot talk/use commands until you accept the rules!"
stringNoMoveUntilConfirm: "You can not move until you accept the rules!"
stringNoChatUntilConfirm: "You can not chat until you accept the rules!"
stringKickPlayerForNotConfirming: "You have not accepted the rules. Disconnecting..."
stringAllowPlayerWithOp: "Welcome back, staff! Remember - you're here to enforce the rules!"
stringAllowPlayerConfirmed: "Permitted player - Rules previously accepted."
stringAllowPlayerBypass: "Age check bypassed by Staff override!"
stringPleaseAcceptRules: "Please read and accept the rules to start playing!"
stringSendWarningHeader: "YOU MUST READ AND AGREE TO THE FOLLOWING RULES:"
stringSendWarningFooter: "To continue, please type the following (exactly as it appears):"
stringAcceptedRules: "Thanks for accepting the rules. Enjoy the game!"

## ---------------------------------------
#  World/butcher settings here
## ---------------------------------------
enableButchering: true
intButcherMobCount: 400